### ISSUE TITLE
Where are the `ray_serialize_interleave_and_shuffle.py` and sampledata files `train-files.txt, traineval-files.txt, test-files.txt`?

### ISSUE THREAD

**Issue by Green-li** [mlfoundations/rtfm#2]
As the title, Can you provide the script and the sample data.

**Comment by jpgard** [comment]
Sorry about the omission! Thanks for filing this issue. These files were just pushed to `main` (the script is called `serialize_interleave_and_shuffle.py`, I will correct this in the README).

Please reopen this issue or create a new one if you have any issues.
