### ISSUE TITLE
How to run inference?

### ISSUE THREAD

**Issue by rjmehta1993** [mlfoundations/rtfm#3]
Can you provide an example on how to run inference?

**Comment by jpgard** [comment]
Thanks for your interest!

We'll provide scripts, tooling, and examples for inference on unlabeled data very soon; they are not a part of the initial release but we are actively working on this! Stay tuned on this issue for updates.

**Comment by rjmehta1993** [comment]
Thanks

**Comment by jpgard** [comment]
We merged in code to support simple inference, take a look at the instructions here: https://github.com/mlfoundations/rtfm?tab=readme-ov-file#quickstart---inference

In case it is not clear, that demo is mostly for *unlabeled* data. If you have *labeled* data and want to evaluate TabuLa on it, we would suggest using the "evaluation" instructions in the main README. 

Closing this but feel free to reopen a new issue, or follow up on this one, if you have any questions!
